version: '3'

services:
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - "$PORT_BINDING:$PORT_BINDING"
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASSWORD"