version: '3'

services:
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - "$LOCAL_PORT_BINDING:$DB_PORT_BINDING"
    environment:
      MYSQL_ROOT_PASSWORD: "$DB_PASSWORD"